---   
server:
  port: 8085
dubbo:
  registry:
    address: zookeeper://172.16.52.10:2181
    dynamic: true
  metadataReport:
    address: zookeeper://172.16.52.10:2181
  configcenter:
    address: zookeeper://172.16.52.10:2181
  protocol:
    port: 20880
    name: dubbo
  application:
    name: yd-web
  consumer:
    timeout: 30000
    retries: 0
    check: false
  scan:
    base-packages: com.yg.web
