---     
server:
  port: 8085
dubbo:
  registry:
    address: zookeeper://10.10.3.32:2181
    dynamic: true
  metadataReport:
    address: zookeeper://10.10.3.32:2181
  configcenter:
    address: zookeeper://10.10.3.32:2181
  protocol:
    port: 20880
    name: dubbo
  application:
    name: qy-web
  scan:
    base-packages: com.yg.web
  consumer:
    timeout: 30000
    retries: 0
