---
spring:
  application:
    name: yd-web
  profiles:
    active: @profiles.active@
  resources:
    static-locations: classpath:/static/,classpath:/public/,file:/home/www/web-deploy/deploy/youdu.guijitech.com/static/
  thymeleaf:
    prefix: file:///home/www/web-deploy/deploy/youdu.guijitech.com/template/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    #default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: true
