---   
server:
  port: 9999
dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
    dynamic: true
  metadataReport:
    address: zookeeper://127.0.0.1:2181
  configcenter:
    address: zookeeper://127.0.0.1:2181
  protocol:
    port: 12345
    name: dubbo
  application:
    name: wb-web
  consumer:
    timeout: 30000
    retries: 0
    check: false
  scan:
    base-packages: com.wb.web
    
    
spring:
    redis:
        database: 0
        host: 127.0.0.1
        password: ''
        pool:
            max-active: 200
            max-idle: 10
            max-wait: -1
            min-idle: 0
        port: 6379
        timeout: 1000

