---
spring:
  datasource:
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 3
    validationQuery: select 'x'
    initialSize: 1
    maxWait: 60000
    filters: stat,wall,slf4j
    poolPreparedStatements: true
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://121.40.70.203:3306/db_yg?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: Wuyc521!
    maxPoolPreparedStatementPerConnectionSize: 20
    testOnBorrow: false
    testWhileIdle: true
    minEvictableIdleTimeMillis: 30000
    timeBetweenEvictionRunsMillis: 60000
    testOnReturn: false
    driverClassName: com.mysql.cj.jdbc.Driver
    maxActive: 20
  
  
dubbo:
  registry:
    address: zookeeper://172.16.52.10:2181
  metadataReport:
    address: zookeeper://172.16.52.10:2181
  configcenter:
    address: zookeeper://172.16.52.10:2181
  protocol:
    port: 20888
    name: dubbo
  scan:
    base-packages: com.yg.service
  provider:
    dynamic: true
    timeout: 30000
    retries: 0
